module.exports=[{
    id: 365,
    title: 'Naruto Online',
    thumbnail: 'https://www.freetogame.com/g/365/thumbnail.jpg',
    short_description: 'A free-to-play MMO based on the popular anime series and manga, developed \r\n' +
      'by Bandai Namco Entertainment. ',
    game_url: 'https://www.freetogame.com/open/naruto-online',
    genre: 'MMORPG',
    platform: 'Web Browser',
    publisher: 'OAS Games',
    developer: 'Bandai Namco',
    release_date: '2016-07-20',
    freetogame_profile_url: 'https://www.freetogame.com/naruto-online'
  },
  {
    id: 475,
    title: 'Genshin Impact',
    thumbnail: 'https://www.freetogame.com/g/475/thumbnail.jpg',
    short_description: 'If you’ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then you’re going to want to check out miHoYo’s Genshin Impact.',
    game_url: 'https://www.freetogame.com/open/genshin-impact',
    genre: 'Action RPG',
    platform: 'PC (Windows)',
    publisher: 'miHoYo',
    developer: 'miHoYo',
    release_date: '2020-09-28',
    freetogame_profile_url: 'https://www.freetogame.com/genshin-impact'
  },
  {
    id: 353,
    title: 'Stein.world',
    thumbnail: 'https://www.freetogame.com/g/353/thumbnail.jpg',
    short_description: 'A free-to-play, browser-based online fantasy role \r\n' +
      'playing game done in an old-school \r\n' +
      '16-bit style.',
    game_url: 'https://www.freetogame.com/open/steinworld',
    genre: 'MMORPG',
    platform: 'Web Browser',
    publisher: 'PG5-Studio UG',
    developer: 'PG5-Studio UG',
    release_date: '2019-04-24',
    freetogame_profile_url: 'https://www.freetogame.com/steinworld'
  },
  {
    id: 367,
    title: 'SAO’s Legend',
    thumbnail: 'https://www.freetogame.com/g/367/thumbnail.jpg',
    short_description: 'A free-to-play browser-based MMO based on the popular anime Sword Art Online.',
    game_url: 'https://www.freetogame.com/open/saos-legend',
    genre: 'MMORPG',
    platform: 'Web Browser',
    publisher: 'GameSprite',
    developer: 'Raycreator Inc.',
    release_date: '2016-06-24',
    freetogame_profile_url: 'https://www.freetogame.com/saos-legend'
  },
  {
    id: 458,
    title: "League of Angels - Heaven's Fury",
    thumbnail: 'https://www.freetogame.com/g/458/thumbnail.jpg',
    short_description: 'A free-to-play, browser-based fantasy online action RPG based loosely on Western mythology!',
    game_url: 'https://www.freetogame.com/open/league-of-angels-heavens-fury',
    genre: 'MMORPG',
    platform: 'Web Browser',
    publisher: 'Gtarcade',
    developer: 'Yoozoo Games',
    release_date: '2020-01-09',
    freetogame_profile_url: 'https://www.freetogame.com/league-of-angels-heavens-fury'
  },
  {
    id: 508,
    title: 'Enlisted',
    thumbnail: 'https://www.freetogame.com/g/508/thumbnail.jpg',
    short_description: 'Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ',
    game_url: 'https://www.freetogame.com/open/enlisted',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Gaijin Entertainment',
    developer: 'Darkflow Software',
    release_date: '2021-04-08',
    freetogame_profile_url: 'https://www.freetogame.com/enlisted'
  },
  {
    id: 511,
    title: 'Phantasy Star Online 2 New Genesis',
    thumbnail: 'https://www.freetogame.com/g/511/thumbnail.jpg',
    short_description: 'The legacy of Phantasy Star Online 2 continues a thousand years later!',
    game_url: 'https://www.freetogame.com/open/pso2-new-genesis',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Sega',
    developer: 'Sega',
    release_date: '2021-06-09',
    freetogame_profile_url: 'https://www.freetogame.com/pso2-new-genesis'
  },
  {
    id: 466,
    title: 'Valorant',
    thumbnail: 'https://www.freetogame.com/g/466/thumbnail.jpg',
    short_description: 'Test your mettle in Riot Games’ character-based FPS shooter Valorant.',
    game_url: 'https://www.freetogame.com/open/valorant',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Riot Games',
    developer: 'Riot Games',
    release_date: '2020-06-02',
    freetogame_profile_url: 'https://www.freetogame.com/valorant'
  },
  {
    id: 57,
    title: 'Fortnite',
    thumbnail: 'https://www.freetogame.com/g/57/thumbnail.jpg',
    short_description: "A free-to-play, standalone mode of Epic Game's Fortnite. ",
    game_url: 'https://www.freetogame.com/open/fortnite-battle-royale',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Epic Games',
    developer: 'Epic Games',
    release_date: '2017-09-26',
    freetogame_profile_url: 'https://www.freetogame.com/fortnite-battle-royale'
  },
  {
    id: 358,
    title: 'Hunter X Hunter Online',
    thumbnail: 'https://www.freetogame.com/g/358/thumbnail.jpg',
    short_description: 'A free-to-play browser MMORPG based on the popular manga and anime.',
    game_url: 'https://www.freetogame.com/open/hunter-x-hunter-online',
    genre: 'MMORPG',
    platform: 'Web Browser',
    publisher: 'Unigame',
    developer: 'Unigame',
    release_date: '2017-04-00',
    freetogame_profile_url: 'https://www.freetogame.com/hunter-x-hunter-online'
  },
  {
    id: 48,
    title: 'Ironsight',
    thumbnail: 'https://www.freetogame.com/g/48/thumbnail.jpg',
    short_description: 'A free-to-play futuristic shooter published by Aeria Games. ',
    game_url: 'https://www.freetogame.com/open/ironsight',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Aeria Games',
    developer: 'Wiple Games',
    release_date: '2018-02-01',
    freetogame_profile_url: 'https://www.freetogame.com/ironsight'
  },
  {
    id: 452,
    title: 'Call Of Duty: Warzone',
    thumbnail: 'https://www.freetogame.com/g/452/thumbnail.jpg',
    short_description: 'A standalone free-to-play battle royale and modes accessible via Call of Duty: Modern Warfare.',
    game_url: 'https://www.freetogame.com/open/call-of-duty-warzone',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Activision',
    developer: 'Infinity Ward',
    release_date: '2020-03-10',
    freetogame_profile_url: 'https://www.freetogame.com/call-of-duty-warzone'
  },
  {
    id: 506,
    title: 'Totally Accurate Battlegrounds',
    thumbnail: 'https://www.freetogame.com/g/506/thumbnail.jpg',
    short_description: 'Take 60 players, throw them on a map together with over 90 weapons, including balloon crossbows, pots and pans, and inflatable hammers, add physics-based parkour and you have Landfall’s Totally Accurate Battlegrounds (TABG).',
    game_url: 'https://www.freetogame.com/open/tabg',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Landfall',
    developer: 'Landfall',
    release_date: '2018-06-06',
    freetogame_profile_url: 'https://www.freetogame.com/tabg'
  },
  {
    id: 8,
    title: 'Trove',
    thumbnail: 'https://www.freetogame.com/g/8/thumbnail.jpg',
    short_description: 'A free to play Sandbox massively multiplayer online role-playing game! ',
    game_url: 'https://www.freetogame.com/open/trove',
    genre: 'MMORPG',
    platform: 'PC (Windows)',
    publisher: 'Trion Worlds',
    developer: 'Trion Worlds',
    release_date: '2015-07-09',
    freetogame_profile_url: 'https://www.freetogame.com/trove'
  },
  {
    id: 4,
    title: 'CRSED: F.O.A.D.',
    thumbnail: 'https://www.freetogame.com/g/4/thumbnail.jpg',
    short_description: 'Take the battle royale genre and add  mystical powers and you have CRSED: F.O.A.D. (Aka Cuisine Royale: Second Edition)',
    game_url: 'https://www.freetogame.com/open/crsed',
    genre: 'Shooter',
    platform: 'PC (Windows)',
    publisher: 'Gaijin Distribution KFT',
    developer: 'Darkflow Software',
    release_date: '2019-12-12',
    freetogame_profile_url: 'https://www.freetogame.com/crsed'
  },
  {
    id: 346,
    title: 'One Piece Online 2',
    thumbnail: 'https://www.freetogame.com/g/346/thumbnail.jpg',
    short_description: 'A free-to-play, browser-based 2D MMORPG based on the immensely popular One Piece franchise.',
    game_url: 'https://www.freetogame.com/open/one-piece-online-2',
    genre: 'MMORPG',
    platform: 'Web Browser',
    publisher: 'JoyGames',
    developer: 'JoyGames',
    release_date: '2015-09-25',
    freetogame_profile_url: 'https://www.freetogame.com/one-piece-online-2'
  },
  {
    id: 498,
    title: 'Blankos Block Party',
    thumbnail: 'https://www.freetogame.com/g/498/thumbnail.jpg',
    short_description: 'What happens when you take the vinyl collectible toy experience and combine it with an open-world multiplayer game? You get Blankos Block Party!\r\n',
    game_url: 'https://www.freetogame.com/open/blankos',
    genre: 'MMO',
    platform: 'PC (Windows)',
    publisher: 'Third Kind Games',
    developer: 'Mythical Games Inc',
    release_date: '2020-12-11',
    freetogame_profile_url: 'https://www.freetogame.com/blankos'
  },
  {
    id: 509,
    title: 'Smash Legends',
    thumbnail: 'https://www.freetogame.com/g/509/thumbnail.jpg',
    short_description: 'Classic fairy tales get wild with 5minlab and LINE Games Corporation’s brawl-action game Smash Legends.',
    game_url: 'https://www.freetogame.com/open/smash-legends',
    genre: 'Fighting',
    platform: 'PC (Windows)',
    publisher: 'LINE Games Corporation',
    developer: '5minlab',
    release_date: '2021-04-13',
    freetogame_profile_url: 'https://www.freetogame.com/smash-legends'
  }]